### ISSUE TITLE
icns 16x16

### ISSUE THREAD

**Issue by nothingismagick** [idesis-gmbh/png2icons#6] opened 2019-06-21 08:33 UTC
From the source code
        // PNG isn't supported for types il32 and is32. If used the Finder will display a scrambled
        // image in list view. However, the Preview app displays them correctly. The alternative
        // types icp5 and icp4 (with PNG support) also don't work in Finder but again in Preview.

So, I'm consuming png2icons in order to create electron apps, and I have run into this brick wall. I was wondering if you might consider working with me to place a bitmap at the 16x16...

**Comment by nothingismagick** [comment] 2019-06-21 10:08
I found a potential solution:

ic14, ic13, ic12, ic11, ic10 as non-premultiplied ARGB bitmaps

See the linked issue.

**Comment by mn4367** [comment] 2019-06-25 08:16
>  I was wondering if you might consider working with me to place a bitmap at the 16x16...

Sure.

> ic14, ic13, ic12, ic11, ic10 as non-premultiplied ARGB bitmaps.

I don't think that there is something wrong with the current state. These types have to be in PNG [format](https://en.wikipedia.org/wiki/Apple_Icon_Image_format#Icon_types) and that's what png2icons currently writes.

As a sample I took the icon from Safari as a reference. It contains the following set:

| Type | Size | Format | png2icns |
| ---- | ---: | ------ | -------- |
| ic10 | 1024 | PNG    | yes      |
| ic09 |  512 | PNG    | yes      |
| ic14 |  512 | PNG    | yes      |
| ic08 |  256 | PNG    | yes      |
| ic13 |  256 | PNG    | yes      |
| ic07 |  128 | PNG    | yes      |
| ic12 |   64 | PNG    | yes      |
| il32 |   32 | ?      | no       |
| ic11 |   32 | PNG    | yes      |
| is32 |   16 | ?      | no       |

The same is true for the Preview app.

So the only types missing are `il32` and `is32`. This [script](https://github.com/jamf/icns-Creator/blob/master/icns_creator.sh) you mentioned [here](https://github.com/quasarframework/app-extension-icon-genie/issues/73) creates `ic05` and `ic04` (ARGB) instead of `il32` and `is32`.

Since I already have an ARGB buffer I'd first try to use this but my suspicion is that they won't work due to some compression which has to be applied for which I don't have any JS code.

**Comment by mn4367** [comment] 2019-06-25 08:37
Forgot to ask: on which platform do you see the problem? I created png2icons mainly to create icns files for Electron apps and so far couldn't see a problem:

![Bildschirmfoto 2019-06-25 um 10 33 25](https://user-images.githubusercontent.com/6379696/60082940-1a312500-9735-11e9-84cd-b0afb762b46f.png)

![Bildschirmfoto 2019-06-25 um 10 31 40](https://user-images.githubusercontent.com/6379696/60082955-1f8e6f80-9735-11e9-8af0-fd966e8fcdaa.png)

This is on Mojave and earlier versions also worked, AFAIR.

**Comment by nothingismagick** [comment] 2019-06-25 08:59
10.12 - but strangely this is only happening with electron-builder, not
electron-packager. Latest MacOS doesn’t have this issue...

Maybe it’s upstream...?

**Comment by mn4367** [comment] 2019-06-25 10:23
I think I have a 10.12 VM, I'll check. That's indeed strange. I'm also using electron-packager and don't have any issues. Maybe electron-builder does something with the icns file.

**Comment by mn4367** [comment] 2019-06-26 13:15
I cannot reproduce the problem on 10.12 with my icons/PNGs. Can you send me the PNG that causes the broken view? I found a problem in the code which may be the reason for the scrambled view, but I'd need your PNG to check (has to do with color depth).

Edit: This could also solve issue #4.

**Comment by mn4367** [comment] 2019-06-26 13:16
Interesting, it turns out that ic04 and ic05 which are created by iconutil on 10.14 aren't supported on 10.12. The Preview app is unable to display them. Unfortunately the problem for icp4 and icp5 still persists but still only in Finder. So far I was unable to get is32 and il32 to display correctly (scrambled), most probably due to the missing Packbits compression. Does anybody have a link for a site that has an implementation for that in JS? I only found code for decompressing it.

**Comment by nothingismagick** [comment] 2019-06-26 13:29
Here is an example. Indeed, it might be colorspace...

https://github.com/quasarframework/app-extension-icon-genie/blob/dev/src/templates/icon/app-icon.png

>

**Comment by mn4367** [comment] 2019-07-04 00:47
I created a [branch](https://github.com/idesis-gmbh/png2icons/tree/test-samples/sample) with test files. Could you please test if the samples work for you? The latest changes should fix #4, #5 and #6. Please see also the changes (README.md) in the [develop](https://github.com/idesis-gmbh/png2icons/tree/develop) branch.

**Comment by mn4367** [comment] 2019-07-06 20:42
Fixed with v2.0.0.

**Closed as completed by mn4367** 2019-07-06 20:42 UTC
